site_name: AC-Electricity
site_url: https://ac-electricity.com/

nav:
  - Home: index.md
  - History of electricity: history.md
  - Physical signals:
    - Quasistatic: physical_signals/quasistatic.md
    - 1st order: physical_signals/1st_order.md
  - Hardware:
    - Battery: hardware/battery.md
    - GPU: hardware/gpu.md
    - Keyboard: hardware/keyboard.md
    - Motherboard: hardware/motherboard.md
    - Processor: hardware/processor.md
    - RAM: hardware/ram.md
  - Home appliances:
    - Air conditioner: home_appliances/air_conditioner.md
    - Bulb: home_appliances/bulb.md
    - CFL Bulb: home_appliances/cfl_bulb.md
    - Dishwasher: home_appliances/dishwasher.md
    - Freezer: home_appliances/freezer.md
    - Fridge: home_appliances/fridge.md
    - LED: home_appliances/led.md
    - Microwave: home_appliances/microwave.md
    - Oven: home_appliances/oven.md
    - Television: home_appliances/television.md
    - Toaster: home_appliances/toaster.md
    - Speaker: home_appliances/speaker.md
    - Stove: home_appliances/stove.md
    - Vacuum cleaner: home_appliances/vacuum.md
    - Washing machine: home_appliances/washing_machine.md
  - Tags: tags/tags.md

copyright: Copyright &copy; 2024 Alexis Carbillet

theme: 
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
  - media: "(prefers-color-scheme: dark)"
    scheme: default
    primary: black
    accent: indigo
    toggle:
      icon: material/toggle-switch-off
      name: Switch to light mode
  - media: "(prefers-color-scheme: light)"
    scheme: slate
    primary: indigo
    accent: indigo
    toggle:
      icon: material/toggle-switch
      name: Switch to dark mode

plugins:
  - blog:
      authors_file: blog/.authors.yml
  - search:
      lang: en
      pipeline:
        - stemmer
        - stopWordFilter
        - trimmer
  - tags:
      tags_file: tags/tags.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/alexiscarbillet
    - icon: fontawesome/solid/envelope
      link: mailto:alexis.carbillet@mines-ales.org
    - icon: fontawesome/brands/android
      link: https://play.google.com/store/apps/developer?id=alexiscarbillet
    - icon: fontawesome/solid/house
      link: https://alexis-carbillet.com/